// AUTO-GENERATED by scripts/gen_portfolio_data.py — do not edit by hand.
// Regenerate after re-running the capture script.

export type PortfolioItem = {
  name: string;
  domain: string;
  url: string;
  /** Detected platform, e.g. "WordPress (WooCommerce)". */
  stack: string;
  /** Filter bucket, e.g. "WordPress". */
  category: string;
  /** Screenshot path under /public, or "" when unavailable. */
  image: string;
  reachable: boolean;
};


/** 50 live sites with captured screenshots. */
export const portfolioLive: PortfolioItem[] = [
  { name: "RAA Investments", domain: "raainvestments.com", url: "https://raainvestments.com/", stack: "WordPress", category: "WordPress", image: "/portfolio/raainvestments-com.jpg", reachable: true },
  { name: "Algorithmicsoftware", domain: "algorithmicsoftware.co.uk", url: "https://algorithmicsoftware.co.uk/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/algorithmicsoftware-co-uk.jpg", reachable: true },
  { name: "9D Breathwork", domain: "9dbreathwork.com", url: "http://9dbreathwork.com/", stack: "GoHighLevel", category: "GoHighLevel", image: "/portfolio/9dbreathwork-com.jpg", reachable: true },
  { name: "Yaisatangwell", domain: "yaisatangwell.com", url: "https://yaisatangwell.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/yaisatangwell-com.jpg", reachable: true },
  { name: "Latus Media", domain: "latusmedia.com", url: "https://latusmedia.com/", stack: "Wix", category: "Wix", image: "/portfolio/latusmedia-com.jpg", reachable: true },
  { name: "Dog Walker St Albans", domain: "pawscape.co.uk", url: "https://pawscape.co.uk/", stack: "Wix", category: "Wix", image: "/portfolio/pawscape-co-uk.jpg", reachable: true },
  { name: "Crown Braiding", domain: "crownbraiding.com", url: "http://crownbraiding.com/", stack: "WordPress", category: "WordPress", image: "/portfolio/crownbraiding-com.jpg", reachable: true },
  { name: "Serikandi Kent", domain: "serikandikent.com", url: "https://serikandikent.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/serikandikent-com.jpg", reachable: true },
  { name: "Eco Fab", domain: "ecofab.ca", url: "https://ecofab.ca/", stack: "WordPress", category: "WordPress", image: "/portfolio/ecofab-ca.jpg", reachable: true },
  { name: "Clearmatrix", domain: "clearmatrix.io", url: "https://clearmatrix.io/", stack: "Custom", category: "Custom", image: "/portfolio/clearmatrix-io.jpg", reachable: true },
  { name: "MasterCut Natural Stone", domain: "mastercutnaturalstone.com", url: "https://www.mastercutnaturalstone.com/", stack: "Wix", category: "Wix", image: "/portfolio/mastercutnaturalstone-com.jpg", reachable: true },
  { name: "HAIRGLO", domain: "hairglo.co.uk", url: "https://hairglo.co.uk/", stack: "Shopify", category: "Shopify", image: "/portfolio/hairglo-co-uk.jpg", reachable: true },
  { name: "WIZ.AI", domain: "wiz.ai", url: "https://www.wiz.ai/", stack: "Custom", category: "Custom", image: "/portfolio/wiz-ai.jpg", reachable: true },
  { name: "PVI-Group", domain: "pvi-group.com", url: "https://pvi-group.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/pvi-group-com.jpg", reachable: true },
  { name: "Chil_Space", domain: "chilspace.com", url: "https://chilspace.com/", stack: "Custom", category: "Custom", image: "/portfolio/chilspace-com.jpg", reachable: true },
  { name: "Little Soleil", domain: "littlesoleil.com.au", url: "https://littlesoleil.com.au/", stack: "Shopify", category: "Shopify", image: "/portfolio/littlesoleil-com-au.jpg", reachable: true },
  { name: "The Victorian Bridal", domain: "thevictorianbridal.com", url: "https://www.thevictorianbridal.com/", stack: "Shopify", category: "Shopify", image: "/portfolio/thevictorianbridal-com.jpg", reachable: true },
  { name: "CCCNC", domain: "cccnc.org", url: "https://cccnc.org/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/cccnc-org.jpg", reachable: true },
  { name: "IA Distribution", domain: "iadistribution.com", url: "https://iadistribution.com/", stack: "WordPress", category: "WordPress", image: "/portfolio/iadistribution-com.jpg", reachable: true },
  { name: "Magic Studio", domain: "magicstudio.it", url: "https://www.magicstudio.it/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/magicstudio-it.jpg", reachable: true },
  { name: "Doug Silton", domain: "dougsilton.com", url: "http://dougsilton.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/dougsilton-com.jpg", reachable: true },
  { name: "SalesOpsForce", domain: "salesopsforce.com", url: "https://salesopsforce.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/salesopsforce-com.jpg", reachable: true },
  { name: "O'Meara Camping", domain: "omearacamping.ie", url: "https://omearacamping.ie/", stack: "WordPress", category: "WordPress", image: "/portfolio/omearacamping-ie.jpg", reachable: true },
  { name: "Zámek Zbiroh", domain: "zbiroh.com", url: "https://zbiroh.com/", stack: "Webflow", category: "Webflow", image: "/portfolio/zbiroh-com.jpg", reachable: true },
  { name: "Sydney Home & Business Services", domain: "servicequest.com.au", url: "https://servicequest.com.au", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/servicequest-com-au.jpg", reachable: true },
  { name: "Laine Law Firm, PLLC", domain: "lainelawfirm.com", url: "https://lainelawfirm.com/", stack: "Custom", category: "Custom", image: "/portfolio/lainelawfirm-com.jpg", reachable: true },
  { name: "Award-Winning Business Coach Dorset", domain: "simonellson.com", url: "https://www.simonellson.com/", stack: "Webflow", category: "Webflow", image: "/portfolio/simonellson-com.jpg", reachable: true },
  { name: "Three Oaks Bespoke Ltd", domain: "threeoaksbespoke.com", url: "https://threeoaksbespoke.com/", stack: "Webflow", category: "Webflow", image: "/portfolio/threeoaksbespoke-com.jpg", reachable: true },
  { name: "Amersham Wellness Co.", domain: "amershamwellnessco.clinic", url: "https://amershamwellnessco.clinic/", stack: "Webflow", category: "Webflow", image: "/portfolio/amershamwellnessco-clinic.jpg", reachable: true },
  { name: "Formé Haus Tring", domain: "formhaustring.co.uk", url: "https://formhaustring.co.uk/", stack: "Webflow", category: "Webflow", image: "/portfolio/formhaustring-co-uk.jpg", reachable: true },
  { name: "Ortak Tekne", domain: "ortaktekne.com", url: "https://ortaktekne.com", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/ortaktekne-com.jpg", reachable: true },
  { name: "VIPER", domain: "joinviper.com", url: "https://joinviper.com/", stack: "WordPress", category: "WordPress", image: "/portfolio/joinviper-com.jpg", reachable: true },
  { name: "FitClub Gym Group", domain: "fitclubgymgroup.co.uk", url: "https://fitclubgymgroup.co.uk/", stack: "Custom", category: "Custom", image: "/portfolio/fitclubgymgroup-co-uk.jpg", reachable: true },
  { name: "Ipswich Glass at Home", domain: "ipswichglassathome.co.uk", url: "https://ipswichglassathome.co.uk/", stack: "Webflow", category: "Webflow", image: "/portfolio/ipswichglassathome-co-uk.jpg", reachable: true },
  { name: "Specialized Med", domain: "specialized-med.com", url: "https://www.specialized-med.com/", stack: "Custom", category: "Custom", image: "/portfolio/specialized-med-com.jpg", reachable: true },
  { name: "Tribune (Webflow)", domain: "whale-press-99789a.webflow.io", url: "https://whale-press-99789a.webflow.io/", stack: "Webflow", category: "Webflow", image: "/portfolio/whale-press-99789a-webflow-io.jpg", reachable: true },
  { name: "MAD Mowers", domain: "madmowers.uk", url: "https://madmowers.uk/", stack: "Wix", category: "Wix", image: "/portfolio/madmowers-uk.jpg", reachable: true },
  { name: "MAD Mowers", domain: "store.madmowers.uk", url: "https://store.madmowers.uk/", stack: "Shopify", category: "Shopify", image: "/portfolio/store-madmowers-uk.jpg", reachable: true },
  { name: "SME Advantage", domain: "smeadvantage.co.uk", url: "https://www.smeadvantage.co.uk/", stack: "Wix", category: "Wix", image: "/portfolio/smeadvantage-co-uk.jpg", reachable: true },
  { name: "DNGR Tech", domain: "dngrtech.com", url: "https://dngrtech.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/dngrtech-com.jpg", reachable: true },
  { name: "Heartbreak Hotel", domain: "heartbreakhotel.no", url: "https://www.heartbreakhotel.no/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/heartbreakhotel-no.jpg", reachable: true },
  { name: "Hocy Vital Drink", domain: "hocy-vitaldrink.com", url: "https://hocy-vitaldrink.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/hocy-vitaldrink-com.jpg", reachable: true },
  { name: "Ohtech", domain: "ohtech.co.uk", url: "https://www.ohtech.co.uk/", stack: "WordPress", category: "WordPress", image: "/portfolio/ohtech-co-uk.jpg", reachable: true },
  { name: "Rural Ranges", domain: "ruralranges.com", url: "https://www.ruralranges.com/", stack: "Shopify", category: "Shopify", image: "/portfolio/ruralranges-com.jpg", reachable: true },
  { name: "ATELIER LIVIANNE", domain: "atelierlivianne.com", url: "https://atelierlivianne.com/", stack: "Custom", category: "Custom", image: "/portfolio/atelierlivianne-com.jpg", reachable: true },
  { name: "Remote Air Service", domain: "remoteairservice.com", url: "https://remoteairservice.com/", stack: "Custom", category: "Custom", image: "/portfolio/remoteairservice-com.jpg", reachable: true },
  { name: "Client landing page", domain: "sites.leadconnectorhq.com", url: "https://sites.leadconnectorhq.com/preview/7N4vmim8Q3gJQzDIwvvj?notrack=true", stack: "GoHighLevel", category: "GoHighLevel", image: "/portfolio/sites-leadconnectorhq-com.jpg", reachable: true },
  { name: "Lolita Ayala Life", domain: "lolitaayala.life", url: "https://www.lolitaayala.life/", stack: "Webflow", category: "Webflow", image: "/portfolio/lolitaayala-life.jpg", reachable: true },
  { name: "36th Street Realty INC", domain: "36threalty.com", url: "https://36threalty.com/", stack: "WordPress", category: "WordPress", image: "/portfolio/36threalty-com.jpg", reachable: true },
  { name: "Global Syngas Association", domain: "globalsyngas.org", url: "https://globalsyngas.org/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "/portfolio/globalsyngas-org.jpg", reachable: true },
];

/** 32 sites currently unreachable (offline / blocking). */
export const portfolioOffline: PortfolioItem[] = [
  { name: "Hireconsultancy", domain: "hireconsultancy.com", url: "https://hireconsultancy.com/", stack: "Custom", category: "Custom", image: "/portfolio/hireconsultancy-com.jpg", reachable: false },
  { name: "Breathmasters", domain: "breathmasters.com", url: "http://breathmasters.com/", stack: "Custom", category: "Custom", image: "/portfolio/breathmasters-com.jpg", reachable: false },
  { name: "Travalisting", domain: "travalisting.com", url: "https://travalisting.com/", stack: "Custom", category: "Custom", image: "", reachable: true },
  { name: "Teachgulf", domain: "teachgulf.com", url: "https://teachgulf.com/", stack: "Custom", category: "Custom", image: "", reachable: false },
  { name: "Jayserene", domain: "jayserene.com", url: "https://jayserene.com/", stack: "Custom", category: "Custom", image: "", reachable: false },
  { name: "Shareestate", domain: "shareestate.net", url: "https://shareestate.net/", stack: "Custom", category: "Custom", image: "/portfolio/shareestate-net.jpg", reachable: false },
  { name: "Dr Juliet", domain: "drjuliet.co.uk", url: "https://drjuliet.co.uk/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "", reachable: true },
  { name: "Fqsconsulting", domain: "fqsconsulting.com", url: "https://fqsconsulting.com/", stack: "Custom", category: "Custom", image: "/portfolio/fqsconsulting-com.jpg", reachable: false },
  { name: "Spectre Group", domain: "spectre-grp.com", url: "https://spectre-grp.com/", stack: "Custom", category: "Custom", image: "/portfolio/spectre-grp-com.jpg", reachable: false },
  { name: "VirtueSQL", domain: "virtuesqlllc.wpenginepowered.com", url: "https://virtuesqlllc.wpenginepowered.com/", stack: "WordPress (WooCommerce)", category: "WordPress", image: "", reachable: true },
  { name: "Ecosessence", domain: "ecosessence.com", url: "https://ecosessence.com/", stack: "Custom", category: "Custom", image: "/portfolio/ecosessence-com.jpg", reachable: false },
  { name: "Maturehealth", domain: "maturehealth.com", url: "https://maturehealth.com/", stack: "Custom", category: "Custom", image: "/portfolio/maturehealth-com.jpg", reachable: false },
  { name: "Skykitchenafrica", domain: "skykitchenafrica.com", url: "https://skykitchenafrica.com/", stack: "Custom", category: "Custom", image: "/portfolio/skykitchenafrica-com.jpg", reachable: false },
  { name: "Efeisaac", domain: "efeisaac.com", url: "http://efeisaac.com", stack: "Custom", category: "Custom", image: "/portfolio/efeisaac-com.jpg", reachable: false },
  { name: "Shannonlambrealty", domain: "shannonlambrealty.com", url: "https://shannonlambrealty.com/", stack: "Custom", category: "Custom", image: "/portfolio/shannonlambrealty-com.jpg", reachable: false },
  { name: "Mediatimesent", domain: "mediatimesent.com", url: "https://mediatimesent.com/", stack: "Custom", category: "Custom", image: "/portfolio/mediatimesent-com.jpg", reachable: false },
  { name: "VKA Org", domain: "vkaorg.wpcomstaging.com", url: "https://vkaorg.wpcomstaging.com/", stack: "WordPress", category: "WordPress", image: "", reachable: false },
  { name: "Pinotecdental", domain: "pinotecdental.com", url: "https://pinotecdental.com/", stack: "Custom", category: "Custom", image: "/portfolio/pinotecdental-com.jpg", reachable: false },
  { name: "Americanwarriorsprotection", domain: "americanwarriorsprotection.com", url: "https://americanwarriorsprotection.com/", stack: "Custom", category: "Custom", image: "", reachable: false },
  { name: "Goldroofs", domain: "goldroofs.net", url: "https://goldroofs.net/", stack: "WordPress", category: "WordPress", image: "", reachable: true },
  { name: "Neurocraft", domain: "neurocraft.ai", url: "https://neurocraft.ai/", stack: "WordPress", category: "WordPress", image: "", reachable: true },
  { name: "Broncodoors", domain: "broncodoors.com", url: "https://broncodoors.com/", stack: "Custom", category: "Custom", image: "/portfolio/broncodoors-com.jpg", reachable: false },
  { name: "Jsnipes", domain: "jsnipes.com", url: "https://jsnipes.com/", stack: "Custom", category: "Custom", image: "/portfolio/jsnipes-com.jpg", reachable: false },
  { name: "Treevo", domain: "treevo.info", url: "https://treevo.info/", stack: "Custom", category: "Custom", image: "/portfolio/treevo-info.jpg", reachable: false },
  { name: "Pavluc", domain: "pavluc.nl", url: "https://pavluc.nl/", stack: "Custom", category: "Custom", image: "/portfolio/pavluc-nl.jpg", reachable: false },
  { name: "exo catering Tinos, Greece", domain: "exo.com.gr", url: "https://www.exo.com.gr/", stack: "WordPress", category: "WordPress", image: "", reachable: true },
  { name: "Starlinegates", domain: "starlinegates.com", url: "https://starlinegates.com/", stack: "WordPress", category: "WordPress", image: "", reachable: true },
  { name: "Lounge14", domain: "lounge14.com", url: "https://lounge14.com", stack: "Custom", category: "Custom", image: "/portfolio/lounge14-com.jpg", reachable: false },
  { name: "Shopify store", domain: "xqrdsc-4p.myshopify.com", url: "https://xqrdsc-4p.myshopify.com/", stack: "Shopify", category: "Shopify", image: "", reachable: false },
  { name: "Trellis Health", domain: "try.jointrellishealth.com", url: "https://try.jointrellishealth.com/", stack: "Webflow", category: "Webflow", image: "/portfolio/try-jointrellishealth-com.jpg", reachable: false },
  { name: "Displaygroupinc", domain: "displaygroupinc.com", url: "https://displaygroupinc.com/", stack: "Custom", category: "Custom", image: "", reachable: true },
  { name: "Genpersonnel", domain: "genpersonnel.com", url: "https://genpersonnel.com/", stack: "Custom", category: "Custom", image: "/portfolio/genpersonnel-com.jpg", reachable: false },
];

export const portfolioCategories = [
  "All",
  "WordPress",
  "Shopify",
  "Webflow",
  "Wix",
  "GoHighLevel",
  "Custom",
] as const;
