"""Generate src/lib/portfolio.ts from the capture manifest."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / "scripts" / "portfolio_manifest.json").read_text(encoding="utf-8"))
OUT = ROOT / "src" / "lib" / "portfolio.ts"

SEP = re.compile(r"\s+[|\u2013\u2014\-:\u00b7]\s+|\s+::\s+")

# Title fragments that mean the captured page is NOT the real site (interstitials,
# challenges, maintenance) — such screenshots are dropped from the visual grid.
UNUSABLE = (
    "checking your browser", "just a moment", "attention required",
    "bot verification", "edge ip", "verify you are human", "ddos",
    "undergoing maintenance", "maintenance mode", "boutique indisponible",
    "store unavailable", "this store is unavailable", "site unavailable",
    "access denied", "forbidden", "security check",
)

# Titles too generic to use as a brand name -> fall back to the domain / override.
GENERIC = (
    "home", "ana sayfa", "try", "welcome", "coming soon", "join the waitlist",
    "index of", "not found", "error", "loading", "página inicial", "accueil",
)

# Hand-curated names for sites whose <title> is a poor brand label.
OVERRIDES = {
    "littlesoleil.com.au": "Little Soleil",
    "thevictorianbridal.com": "The Victorian Bridal",
    "whale-press-99789a.webflow.io": "Tribune (Webflow)",
    "ortaktekne.com": "Ortak Tekne",
    "remoteairservice.com": "Remote Air Service",
    "drjuliet.co.uk": "Dr Juliet",
    "latusmedia.com": "Latus Media",
    "cccnc.org": "CCCNC",
    "omearacamping.ie": "O'Meara Camping",
    "globalsyngas.org": "Global Syngas Association",
    "salesopsforce.com": "SalesOpsForce",
    "dngrtech.com": "DNGR Tech",
    "ruralranges.com": "Rural Ranges",
    "specialized-med.com": "Specialized Med",
    "virtuesqlllc.wpenginepowered.com": "VirtueSQL",
    "try.jointrellishealth.com": "Trellis Health",
    "vkaorg.wpcomstaging.com": "VKA Org",
    "spectre-grp.com": "Spectre Group",
    "xqrdsc-4p.myshopify.com": "Shopify store",
}


# Domains to keep out of the visual grid:
#  - travalisting.com: parked GoDaddy placeholder
#  - virtuesqlllc...: serves a reCAPTCHA challenge, not the site
#  - drjuliet / exo: real sites, but a JS slider / infinite preloader can't be
#    screenshotted cleanly in headless — listed in "Also delivered" instead.
EXCLUDE_LIVE = {
    "travalisting.com",
    "virtuesqlllc.wpenginepowered.com",
    "drjuliet.co.uk",
    "exo.com.gr",
}


def host_of(url: str) -> str:
    h = re.sub(r"^https?://", "", url).split("/")[0]
    return h.replace("www.", "")


def has_ascii_letter(s: str) -> bool:
    return any(c.isalpha() and ord(c) < 128 for c in s)


def usable_screenshot(rec) -> bool:
    title = (rec.get("title") or "").lower()
    return not any(u in title for u in UNUSABLE)


def display_name(rec) -> str:
    host = host_of(rec["primary"])
    if host in OVERRIDES:
        return OVERRIDES[host]
    if "leadconnectorhq.com" in host:
        return "Client landing page"
    title = (rec.get("title") or "").strip()
    if title:
        name = re.sub(r"\s+", " ", SEP.split(title)[0].strip())
        low = name.lower()
        ok = (
            2 <= len(name) <= 42
            and low not in GENERIC
            and not any(u in low for u in UNUSABLE)
            and has_ascii_letter(name)
            and name[0].isalnum()
        )
        if ok:
            return name
    # Prettify domain: first label is the brand (handles .co.uk / .com.au).
    base = host.split(".")[0]
    tokens = re.split(r"[-_]", base)
    return " ".join(t.capitalize() for t in tokens if t) or host


def category(stack: str) -> str:
    if stack.startswith("WordPress"):
        return "WordPress"
    return stack


def esc(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


live, offline = [], []
for r in data:
    image = r.get("screenshot") or ""
    if not usable_screenshot(r) or host_of(r["primary"]) in EXCLUDE_LIVE:
        image = ""  # challenge/maintenance interstitial or parked placeholder
    item = {
        "name": display_name(r),
        "domain": host_of(r["primary"]),
        "url": r["primary"],
        "stack": r["stack"],
        "category": category(r["stack"]),
        "image": image,
        "reachable": bool(r["reachable"]),
    }
    (live if r["reachable"] and image else offline).append(item)


def ts_obj(o) -> str:
    fields = ", ".join(
        f'{k}: "{esc(str(v))}"' if isinstance(v, str) else f"{k}: {str(v).lower()}"
        for k, v in o.items()
    )
    return "  { " + fields + " },"


header = '''// AUTO-GENERATED by scripts/gen_portfolio_data.py — do not edit by hand.
// Regenerate after re-running the capture script.

export type PortfolioItem = {
  name: string;
  domain: string;
  url: string;
  /** Detected platform, e.g. "WordPress (WooCommerce)". */
  stack: string;
  /** Filter bucket, e.g. "WordPress". */
  category: string;
  /** Screenshot path under /public, or "" when unavailable. */
  image: string;
  reachable: boolean;
};

'''

lines = [header]
lines.append(f"/** {len(live)} live sites with captured screenshots. */")
lines.append("export const portfolioLive: PortfolioItem[] = [")
lines += [ts_obj(o) for o in live]
lines.append("];")
lines.append("")
lines.append(f"/** {len(offline)} sites currently unreachable (offline / blocking). */")
lines.append("export const portfolioOffline: PortfolioItem[] = [")
lines += [ts_obj(o) for o in offline]
lines.append("];")
lines.append("")
cats = []
for o in live:
    if o["category"] not in cats:
        cats.append(o["category"])
order = ["WordPress", "Shopify", "Webflow", "Wix", "GoHighLevel", "Custom"]
cats_sorted = [c for c in order if c in cats] + [c for c in cats if c not in order]
lines.append("export const portfolioCategories = [")
lines.append('  "All",')
lines += [f'  "{c}",' for c in cats_sorted]
lines.append("] as const;")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT}  live={len(live)} offline={len(offline)} categories={cats_sorted}")
